### ISSUE TITLE
Failure on a FZN example

### ISSUE THREAD

**Issue by glebbelov** [Gecode/gecode#101]
**Describe the bug**

Reports UNSAT while OR-Tools says SAT

**To Reproduce**

`fzn-gecode ../challenge_from_2012/mznc12-problems/tpp/tpp.fzn`

[tpp.fzn.tar.gz](https://github.com/Gecode/gecode/files/5885478/tpp.fzn.tar.gz)

**Gecode and Platform Configuration**

Please describe which version of Gecode you use, on which operating system, and with which C++ compiler (including its version).

Using current Gecode develop, Ubuntu 19.10, GCC 8.3.0

**Comment by zayenz** [comment]
This appears to have been the same issue as #109, and is now fixed in release/6.3.0 and develop.
