### ISSUE TITLE
Uninitialized memory in int/channel/dom.hpp

### ISSUE THREAD

**Issue by mattiasgronkvist** [Gecode/gecode#128]
**Describe the bug**

When running our test suite using the valgrind/memcheck tool, we discovered that the `assigned` variable on line 256 in gecode/int/channel/dom.hpp can end up uninitialized. This is a problem as it is used in an if statement on line 258, triggering a 'Conditional jump or move depends on uninitialised value(s)' warning in memcheck. 

Clearly, the code expects that the `distinct` `propagate()` call on line 257 will set the `assigned` variable, but it is pretty straightforward to see that the `assigned` reference parameter is not always assigned a value in `propagate()`. 

I don't know how serious this issue is, but we have not observed any actual bad behavior except for the memcheck warning. It also seems clear that the `distinct` propagator is called with an uninitialized `assigned` variable in a few other cases in the code.

**To Reproduce**

I don't know of a simple way to reproduce the problem outside of our internal test case, but it should be fairly straightforward to manually find the issue from the description above.
 
**Gecode and Platform Configuration**

Gecode 6.2.0
Red Hat Enterprise Linux 7
g++ (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
Valgrind-3.15.0

**Comment by zayenz** [comment]
Thanks for the report, it does indeed look like unitialized reads happen, which is a bug.

I've fixed it locally by moving the assignement of false to assigned up from prune into propagate. I am running relevant tests to see that it works before pushing to the branch for the upcoming release.

**Comment by mattiasgronkvist** [comment]
Thanks for the exceptional turnaround time! Is there a timeline for the next release?

**Comment by zayenz** [comment]
There is no fixed time-plan, although we are planning for it again and hope to officially mark it as released soon-ish. 

The main hold-ups have been testing on Windows and packaging. Unfortunately Christian had all the scripts and know-how on how to create pre-compiled release versions. Therefore it will be a source only release, at least for now.

The branch we plan to release is `release/6.3.0` so you can try it out if you want.

**Comment by zayenz** [comment]
Fixed in commit 0f89064
