### ISSUE TITLE
Maximum/Minimun solution searching

### ISSUE THREAD

**Issue by ageromin** [Gecode/gecode#14]
Hello Christian,

I want to find the maximum and minimum value associated to a solution space. The functions .min() and .max() seem not to work with a two variable equation. The program returns the good solutions but the function .min() and .max() return the initial maximum and minimum value of the domain definition without taking care of the equation.
Do you find any error on our code ?

Here our program 
We are using GeCode version 6.0.1 2017
`#include` <gecode/minimodel.hh>
#include <gecode/driver.hh>
#include <gecode/search.hh>
#include <gecode/float.hh>
#include <gecode/int.hh>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <string>

using namespace std;
using namespace Gecode;

class plan : public Script {

protected:
IntVar x,y;

public:
plan(const Options& opt) : Script(opt), x(*this, 0,20) , y(*this, 0, 20) {

rel(*this, (x+y)<=13);     

branch(*this, x, INT_VAL_MAX());
branch(*this, y, INT_VAL_MAX());

std::cout << "\n\nxmin : " << x.min() << "   xmax : " << x.max()
<< "\nymin : " << y.min() << "   ymax : " << y.max()<<endl;
}

virtual void
print(std::ostream& os) const {

os << "\nx: " << x << "  y: " << y;
}

plan(plan& s) : Script(s) {

x.update(*this, s.x);
y.update(*this, s.y);
}

virtual Space* copy(void) {
return new plan(*this);
}
};

int main(int argc, char* argv[])               
{
Options opt("Plan");
opt.solutions(0);
Script::run<plan, BAB, Options>(opt);

return 0;

}`

Thank you for your time.

Anthony.

**Comment by chschulte** [comment]
Read in MPG about best solution search.
