### ISSUE TITLE
Performance difference if compiled with CMake vs Autotools

### ISSUE THREAD

**Issue by 95A31** [Gecode/gecode#154]
Hello,
I am noticing a big solving time difference if I compile fzn-gecode (release/6.3.0) with cmake
```
mkdir build
cd build
cmake ..
make -j 8
```
and autotools
```
./configure
make
```
I am using the following command line 
```
./fzn-gecode -s -n 260 ./400x200.fzn
```
with [this](https://pastebin.com/zQKQh7U3) model.

**Comment by Dekker1** [comment]
CMake will produce a debug build by default. If you set the CMake build type to release, it will likely produce much more competitive binaries: https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

**Comment by zayenz** [comment]
As @Dekker1 mentioned, the default of compilation with debug/release mode is different.
