### ISSUE TITLE
Is gecode still being maintained?

### ISSUE THREAD

**Issue by marcovc** [Gecode/gecode#157]
Hi!

I am considering Gecode for a large project. It seems the last release was in 2019. Is this project still being maintained?

Thank you
Marco

**Comment by sirwhinesalot** [comment]
The release/6.3.0 branch had its last commit in July 2022, so I'd suggest using that branch (seems to be working quite well from my experiments).

I have no idea why the team hasn't officially released 6.3.0, it's already part of MiniZinc...

**Comment by zayenz** [comment]
Hi,

It's me, I'm team 😀

Yes, it is maintained and the plan is to release release/6.3.0 as a release, potentially/probably with a fix for the problem reported in #156 

The original problem was that we lost all the release knowledge with the passing of Christian. This included the building of the very popular pre-built packages for Windows. Recently, Filip Konvička has done some amazing wqork to help me out with that. In addition, I have not finished updating Modelling and Programming with Gecode, to ensure that all the code is correct.

It is a clear problem that we don't have much resources to push the project forward, but I value keeping Gecode alive a lot. I hope that I will be able to get a better cadence in the future.

**Comment by marcovc** [comment]
That is great news, thank you!
