### ISSUE TITLE
table_int_reif for 

### ISSUE THREAD

**Issue by satishmp** [Gecode/gecode#17]
Hello Christian,
  The current table constraint in a reified context hits this assert when array length(x) > 5.
"'table' constraints in a reified context are only supported for 1..5 variables."
I wrote a version that works for any length of "x".
There is one issue though, the mzn2fzn binary consumes 3Gig memory when length(x) = 6, dom_size(x[]) = 7, may be because the generated table has large number of rows. (6^7 rows).

Pl. see attached file.

table_int_reif.txt
[table_int_reif.txt](https://github.com/Gecode/gecode/files/2252992/table_int_reif.txt)

Thanks,
Satish Majhee

**Comment by chschulte** [comment]
Guido, can you have a look, please! Thanks and cheers Christian

**Comment by guidotack** [comment]
The reified table constraint is imported from the MiniZinc standard library, so we won't update it in Gecode (otherwise the Gecode behaviour would be inconsistent with other MiniZinc solvers). You can submit this as a feature request for MiniZinc.
