### ISSUE TITLE
MiniModel pow for FloatVar does not fail space for base assigned to zero and negative exponent

### ISSUE THREAD

**Issue by msbalzer** [Gecode/gecode#28]
The following test case will fail:

    FloatVar x {home, 0, 0};
    int const n {-1};
    FloatVar y {home, Float::Limits::min, Float::Limits::max};

    rel (home, y == pow (x, n));
    home.status();

    EXPECT_TRUE (home.failed());

The origin seems to be the special treatment in `minimodel/float-arith.cpp` which does not take into account the exponent:
https://github.com/Gecode/gecode/blob/801849d12e8e598c2f4787758f98290df77c33f7/gecode/minimodel/float-arith.cpp#L202

**Comment by chschulte** [comment]
Fixed. However, your example is meant to throw an exception...
