### ISSUE TITLE
 Error: Gecode: Float::linear: Number out of limits

### ISSUE THREAD

**Issue by lalithsuresh** [Gecode/gecode#29]
Reposting from https://github.com/MiniZinc/libminizinc/issues/246

I have a Minizinc model where my objective function is a combination of floats and it triggers the following error: `Error: Gecode: Float::linear: Number out of limits.`

Here's a simplified version of the model to reproduce the bug. hostCost in this example could very well be an integer instead, but my actual model requires 'hostCost' to be a float.

```
int: numVms = 3;
array[1..numVms] of int : vmId = [1, 2, 3];
array[1..numVms] of var int : vmHost;
array[1..numVms] of int : vmRequest = [1, 1, 1];

int: numHosts = 3;
array[1..numHosts] of int : hostId = [1, 2, 3];
array[1..numHosts] of int : hostCapacity = [3, 3, 3];

array[1..numHosts] of var float : hostCost = 
            [hostCapacity[host] - sum([vmRequest[v] | h in 1..numHosts, v in 1..numVms where vmHost[v] == hostId[h]   /\ hostId[h] == hostId[host]]) | host in hostId];
                                              
solve maximize min(hostCost) - max(hostCost);
```

I don't see why this model should be running into floating point issues?

**Comment by chschulte** [comment]
See my reply there. Not a bug.

**Comment by zaynabzaynab** [comment]
what is the solution for the problem cause I have the same thing going on with my code
