### ISSUE TITLE
can't use gecode after installing it on macOS

### ISSUE THREAD

**Issue by wsgdrfz** [Gecode/gecode#36]
Hi, I have installed gecode following the MPG 2.6 but still can't use it.
- `gcc -c queens.cpp
queens.cpp:42:10: fatal error: 'gecode/driver.hh' file not found
#include <gecode/driver.hh>`

- `g++ -stdlib=libstdc++ -framework gecode -o queen queens.cpp
clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command
      line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
queens.cpp:42:10: fatal error: 'gecode/driver.hh' file not found
#include <gecode/driver.hh>
         ^~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.`

- Using Makefile:
```EXECUTABLES = queens
SRCS = $(EXECUTABLES:%=%.cpp)
OBJS = $(EXECUTABLES:%=%.o)

CXX = g++
CXX_FLAGS = -std=c++11 -Wall -O3
LIBS = -framework gecode
RM = rm -f

all: $(EXECUTABLES)

$(EXECUTABLES): %: %.o
	$(CXX) $(CXX_FLAGS) -o $@ $^ $(LIBS)

%.o: %.cpp
	$(CXX) $(CXX_FLAGS) -c -o $@ $^

# You can run your experiments from the Makefile like this (requires queens01 to run)
res.tex: queens queens01
	./gather_stats.py --range 8:_:15 --timeout 10 \
	--model queens --model queens01 > res.tex

clean:
	$(RM) $(OBJS) $(EXECUTABLES)
```
Output:
`make queens
g++ -std=c++11 -Wall -O3 -c -o queens.o queens.cpp
queens.cpp:42:10: fatal error: 'gecode/driver.hh' file not found
#include <gecode/driver.hh>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [queens.o] Error 1`

**Comment by chschulte** [comment]
Guido, could you have look?

**Comment by wsgdrfz** [comment]
I have successfully installed it on Linux but not mac. Thanks.

**Comment by guidotack** [comment]
The default search path for frameworks has changed on macOS, you now have to add the following to your CXX_FLAGS:
`CXX_FLAGS = -F/Library/Frameworks ...`

Can you let us know if that fixes the problem? If it does we will change the documentation.
