### ISSUE TITLE
Wrong handling of exp(0) in MiniModel for floats

### ISSUE THREAD

**Issue by ConradDrescher** [Gecode/gecode#43]
Hi there,

here's a small issue:

**Describe the bug**

In minimodel/float-arith.cpp there is the following:

       case ANLFE_EXP:
         {
           assert(n == 1);
           FloatVar x = a[0].post(home);
           if (x.assigned() && (x.val() == 0.0))
             y = result(home,ret,x);
           else {
             y = result(home,ret);
             exp(home, x, y);
           }
         }
         break;

which in the if-branch says that exp(0) = 0 - but that should be 1.

**To Reproduce**

Should be possible to trigger.

**Gecode and Platform Configuration**

As seen in the dev-branch and older releases.

**Comment by chschulte** [comment]
Thanks, fixed in develop.
