### ISSUE TITLE
Missing "post" event in trace

### ISSUE THREAD

**Issue by ConradDrescher** [Gecode/gecode#44]
**Describe the bug**

Hi there,

when posting constraints in a space after having already called status() on that space I am missing the post-events, but get the propagate-events once status() is called a second time.

Many thanks and all the best
Conrad

**To Reproduce**

    Gecode::IntVarArray x(*this, 3);
    for(int i=0; i<3; ++i)
        x[i] = Gecode::IntVar(*this, -25, 25);

    Gecode::Home home(*this);

    Gecode::trace(home, (Gecode::TE_PROPAGATE | Gecode::TE_POST));

    Gecode::PropagatorGroup pba, pbb;

    Gecode::rel(pba(home),  x[0] == x[1]);
    Gecode::rel(pba(home),  x[1] == x[2]);

// comment out this call and the post-events for pbb go missing
//    this->status();

// make the space fail
    Gecode::rel(pbb(home), x[0] == 1);
    Gecode::rel(pbb(home), x[2] == 2);

    this->status();

**Gecode and Platform Configuration**

Please describe which version of Gecode you use, on which operating system, and with which C++ compiler (including its version).

Gecode 6.1.1 on Linux with gcc 7.3

**Comment by chschulte** [comment]
Hi Conrad,

Yes, this is really weird. I have to look more carefully what's going on...

Cheers, Christian

**Comment by chschulte** [comment]
The whole event recording logic was broken and will have not worked after calling status(). Fixed now.
