### ISSUE TITLE
warning Use of the header <ext/hash_map> is deprecated.  Migrate to <unordered_map>

### ISSUE THREAD

**Issue by yurivict** [Gecode/gecode#53]
clang8 prints many warnings like this on FreeBSD 12:
```
In file included from ./gecode/flatzinc/lexer.lxx:54:
In file included from /usr/ports/devel/gecode/work/gecode-release-6.2.0/gecode/flatzinc/parser.hh:65:
In file included from /usr/ports/devel/gecode/work/gecode-release-6.2.0/gecode/flatzinc/symboltable.hh:42:
/usr/include/c++/v1/ext/hash_map:213:5: warning: Use of the header <ext/hash_map> is deprecated.  Migrate to <unordered_map> [-W#warnings]
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate to <unordered_map>
    ^
1 warning generated.
```

**Comment by chschulte** [comment]
This is really strange and should never occur: the configure checks whether unordered_map is available and this should automatically be used then.

@guidotack: can you have a look?

@yurivict: can you check whether the configure test for unordered_map is successful on your platform?

**Comment by yurivict** [comment]
> can you check whether the configure test for unordered_map is successful on your platform?

"unordered_map" doesn't appear in the configure output.

**Comment by chschulte** [comment]
Would you mind trying the develop branch? Then the warnings should not be there…

Thanks & Cheers
Christian

--
Christian Schulte, https://chschulte.github.io/
Professor of Computer Science
Software and  Computer Systems
School of Electrical Engineering and Computer Science
KTH Royal Institute of Technology, Sweden

**Comment by yurivict** [comment]
Ok, thanks. I reported this so that they are fixed. If you fixed it please close the issue.

**Comment by chschulte** [comment]
This is weird, I just tried clang 6 and do not get the warnings. Could you send me the config.log file?

**Comment by chschulte** [comment]
Oh, BTW, this was fixed in 2014, that's why it is so weird.

**Comment by yurivict** [comment]
you should use clang 8 or 9. Also the STL lib could be different, the warning comes from it.

**Comment by chschulte** [comment]
Tried clang 8 on Ubuntu. No warnings. Without the config.log file this cannot be resolved as something will have gone wrong there. Hence I close it.

**Comment by yurivict** [comment]
I don't understand why don't you just remove the use of ```ext/hash_map``` and how can config.log help.

This C++ section causes the warning:
```

#if __DEPRECATED
#if defined(_LIBCPP_WARNING)
    _LIBCPP_WARNING("Use of the header <ext/hash_map> is deprecated.  Migrate to <unordered_map>")
#else
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate to <unordered_map>
#endif
#endif
```

It has been put their by the authors of the STL library, they presumably know what is deprecated.

**Comment by chschulte** [comment]
The thing is the following: I do not understand why this is picked up at all, the Gecode configure should have found that unordered_map is available which it didn’t. In that case hash_map would have never been looked at.

So something during configure went wrong. That’s why I want to look at the config.log.

--
Christian Schulte, https://chschulte.github.io/
Professor of Computer Science
Software and Computer Systems
School of Electrical Engineering and Computer Science
KTH Royal Institute of Technology, Sweden

**Comment by yurivict** [comment]
https://people.freebsd.org/~yuri/gecode-config.log

**Comment by chschulte** [comment]
Oh, I see, thanks. I didn’t see that you are using cmake, the default way is using configure. I’ll have a look.

--
Christian Schulte, https://chschulte.github.io/
Professor of Computer Science
Software and Computer Systems
School of Electrical Engineering and Computer Science
KTH Royal Institute of Technology, Sweden

**Comment by chschulte** [comment]
Done
