### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Gecode/gecode#63]
I would like to point out that an identifier like “[`__GECODE_SEARCH_HH__`](https://github.com/Gecode/gecode/blob/2925392ac7a0c8a7b33aaee51721d84725605919/gecode/search.hh#L42 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
[Will further source code places be adjusted](https://github.com/Gecode/gecode/blob/d8e4fa2e55c97de7cd75a7a05f80e84eacd7faec/gecode/kernel/branch/view-sel.hpp#L42 "Update candidate: ViewSel class")?

**Comment by zayenz** [comment]
Good point @elfring, I should fix those also.

**Comment by zayenz** [comment]
@elfring All the remaining cases in Gecode proper that I found have been fixed.

**Comment by zayenz** [comment]
Found a few additional places in code generated from macros, and fixed those in PR #78.
