### ISSUE TITLE
MiniModel does not handle comparison with non-linear Float expression properly

### ISSUE THREAD

**Issue by msbalzer** [Gecode/gecode#7]
The following example will fail home:

    FloatVar x {home, 0, 1};
    rel (home, -1 < abs (x));
    home.status();

In the switch statement at https://github.com/Gecode/gecode/blob/504995fc9edce1e9d28a5b999e6da6bdbe529648/gecode/minimodel/float-expr.cpp#L162 the cases `FRT_LE` and `FRT_GR` seem to be missing.

**Comment by chschulte** [comment]
Fixed in develop.
