### ISSUE TITLE
Add Search Options to Script::run

### ISSUE THREAD

**Issue by ngocbh** [Gecode/gecode#71]
I am trying to add Stop object to limit the running time of the GraphColor model. I read other examples and even documentation and I don't know to both use SizeOption and Search Option on this problem. I am a newbie, Could you help me do this?

https://github.com/Gecode/gecode/blob/master/examples/graph-color.cpp

`opt.parse(argc,argv);`
 `Search::Stop* stop = Search::Stop::time(10000);`
 `Search::Options search_opt;`
 `search_opt.stop = stop;`
  `Script::run<GraphColor,BAB,SizeOptions>(opt);`

**Comment by zayenz** [comment]
You can use the time method on SizeOptions to set a timeout when running using the script driver. https://www.gecode.org/doc-latest/reference/classGecode_1_1Options.html#aba5a26c14a9cb1cdffccaf4e7de399d3

**Comment by ngocbh** [comment]
@zayenz  I did it, thank you so much. But I got another problem where my problem is the optimization, It seems that Gecode only treats a candidate as a solution when it reaches the optimal value. Consequently, I cannot get the solution if I stop searching midway. 
Could I get the best candidate up to the time I stop searching?

**Comment by zayenz** [comment]
Gecode, as all constraint solvers I am aware of, optimize using a branch
and bound procedure. Each time a solution is found, a new constraint is
added saying that the next solution msu tbe better. The last solution found
after the search ends is thus the best/optimal solution (if the search is
allowed to terminate).

In other words, Gecode does exactly what you ask for.

**Comment by ngocbh** [comment]
@zayenz I used `opt.time(10000)` but it showed the message like this:

```
Search engine stopped...
	reason: time limit reached

Initial
	propagators: 4201
	branchers:   2

Summary
	runtime:      10.004 (10004.274 ms)
	solutions:    0
	propagations: 39362738
	nodes:        42215
	failures:     21098
	restarts:     0
	no-goods:     0
	peak depth:   39
```
How can I print the last solution? It seems Gecode does not call the print function in GraphColor class.

**Comment by zayenz** [comment]
The output posted means that no solution satisfying the constraints has been found, so there is no solution to print.

**Comment by ngocbh** [comment]
@zayenz I found my problem. Branching on the number of colors from min value leads to exploring the failures branch before. Thank you for your help.
