### ISSUE TITLE
Build fails with Bison 3.7

### ISSUE THREAD

**Issue by kaol** [Gecode/gecode#77]
Debian updated to Bison 3.7 and building Gecode 6.2.0 fails with it. The gecode/flatzinc/parser.tab.cpp file it generates has an `#include "parser.tab.hpp"` directive in it and since make renames parser.tab.hpp as parser.tab.hh, that fails.

I fixed  it for Debian by adding this to the gecode/flatzinc/parser.tab.cpp target in Makefile.in:
```
sed -i 's/^#include "parser.tab.hpp"/#include "parser.tab.hh"/' gecode/flatzinc/parser.tab.cpp
```

**Comment by zayenz** [comment]
This has been fixed in develop now, and will be in the next release.
