### ISSUE TITLE
Makefile rule removes source files

### ISSUE THREAD

**Issue by ugeorge** [Gecode/gecode#8]
The rule `make distclean` removes source files from the master branch. After calling it, this is (partially) the output of `git status`:

	deleted:    Makefile.dep
	deleted:    gecode/flatzinc/parser.tab.hh
	deleted:    gecode/kernel/var-imp.hpp
	deleted:    gecode/kernel/var-type.hpp

Calling `make` after `make distclean` ends up in an error, unless I reset the local repository (e.g. `git reset --hard`)

**Comment by chschulte** [comment]
That's really a feature as it removes generated files. Running make depend afterwards regenerates these files. I know, not perfect but works ok.
