### ISSUE TITLE
Usage of copy constructor of Gecode::Space causes "Conditional jump or move depends on uninitialised value(s)" in destructor

### ISSUE THREAD

**Issue by fantyg** [Gecode/gecode#93]
**Describe the bug**

After raw usage of Gecode::Space copy constructor valgrind spotted  "Conditional jump or move depends on uninitialised value(s)" in ~Gecode::Space which may lead to segfault.

**To Reproduce**
```c++
#include <gecode/kernel.hh>
class MySpace : public Gecode::Space
{
public:
    MySpace() = default;
    MySpace(MySpace& other) :
        Gecode::Space(other)
    {
    }

    Gecode::Space* copy() override
    {
        return new MySpace(*this);
    }
};

int main()
{
    MySpace s1;
    MySpace s2(s1);
}
```

Compiled with:
```
gcc main.cpp -o out -lgecodesupport -lgecodekernel --std=c++11 -lstdc++ -g -O0
```

Valgrind ran with command:
```
valgrind  ./out
```

Valgrind output:
```
==32653== Memcheck, a memory error detector
==32653== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==32653== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==32653== Command: ./out
==32653== 
==32653== Conditional jump or move depends on uninitialised value(s)
==32653==    at 0x489C823: Gecode::Space::~Space() (in /usr/lib/libgecodekernel.so.49.0)
==32653==    by 0x10AA39: MySpace::~MySpace() (main.cpp:3)
==32653==    by 0x10A29A: main (main.cpp:22)
==32653== 
==32653== 
==32653== HEAP SUMMARY:
==32653==     in use at exit: 0 bytes in 0 blocks
==32653==   total heap usage: 6 allocs, 6 frees, 209,016 bytes allocated
==32653== 
==32653== All heap blocks were freed -- no leaks are possible
==32653== 
==32653== Use --track-origins=yes to see where uninitialised values come from
==32653== For lists of detected and suppressed errors, rerun with: -s
==32653== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Gecode and Platform Configuration**

Gecode 6.2.0
gcc 10.2.0
Valgrind 3.16.1
Linux Manjaro 20.1 kernel 5.7.17-2

**Comment by zayenz** [comment]
The raw copy-constructor of a Space is not intended to be called directly. Instead, if you want to create a clone of a space, call the [clone](https://www.gecode.org/doc-latest/reference/group__TaskSearch.html#gab9c0ee46ceb11cfe4d1fa75188047890) member function. 

I see that this might need to be documented better.

Thanks for reporting though!

**Comment by zayenz** [comment]
Added tip in MPG (https://github.com/Gecode/MPG/commit/7c054426db5293074745202008e653cc82bc0f2c) and additional documentation in the gecode sources (https://github.com/Gecode/gecode/commit/350df215cbcf1af8cd7217e467316482c02748d2).
